trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Build Solution'
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '9.0.x'

          - task: NuGetToolInstaller@1
            displayName: 'Install NuGet'

          - task: NuGetCommand@2
            displayName: 'Restore NuGet packages'
            inputs:
              restoreSolution: '**/*.sln'

          - task: VSBuild@1
            displayName: 'Build solution'
            inputs:
              solution: '**/*.sln'
              platform: 'Any CPU'
              configuration: 'Release'

  - stage: Test
    displayName: 'Test Stage'
    dependsOn: Build
    jobs:
      - job: RunTests
        displayName: 'Run Unit Tests'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Run all unit tests'
            inputs:
              command: 'test'
              projects: '**/*Tests.csproj'
              arguments: '--configuration Release --collect:"XPlat Code Coverage"'

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Test
    jobs:
      - deployment: DeployWebApp
        displayName: 'Deploy to Azure Web App'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure App Service'
                  inputs:
                    azureSubscription: 'AzureConnection-CarSim'
                    appType: 'webApp'
                    appName: 'carsimulatorapp123younes'
                    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
